// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj4hxLAf9nfi3rAWAlGh9otX2AZVnhzMc',
    appId: '1:840116736815:web:65c424ea679775c4c107da',
    messagingSenderId: '840116736815',
    projectId: 'green-farm-game',
    authDomain: 'green-farm-game.firebaseapp.com',
    storageBucket: 'green-farm-game.firebasestorage.app',
    measurementId: 'G-979ZRGJ1L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmCQM5DcAEATC1hIhPYTqZHpyLDq6KxL0',
    appId: '1:840116736815:android:e013249782896b9ac107da',
    messagingSenderId: '840116736815',
    projectId: 'green-farm-game',
    storageBucket: 'green-farm-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAAsCqrNcw7XfsTNkb_cpAfeKGgj-VB1w',
    appId: '1:840116736815:ios:bcc30f67c5978c08c107da',
    messagingSenderId: '840116736815',
    projectId: 'green-farm-game',
    storageBucket: 'green-farm-game.firebasestorage.app',
    iosBundleId: 'com.example.greenFarmGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAAsCqrNcw7XfsTNkb_cpAfeKGgj-VB1w',
    appId: '1:840116736815:ios:bcc30f67c5978c08c107da',
    messagingSenderId: '840116736815',
    projectId: 'green-farm-game',
    storageBucket: 'green-farm-game.firebasestorage.app',
    iosBundleId: 'com.example.greenFarmGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj4hxLAf9nfi3rAWAlGh9otX2AZVnhzMc',
    appId: '1:840116736815:web:b040bf2b2d5effabc107da',
    messagingSenderId: '840116736815',
    projectId: 'green-farm-game',
    authDomain: 'green-farm-game.firebaseapp.com',
    storageBucket: 'green-farm-game.firebasestorage.app',
    measurementId: 'G-X39ZYSS7P0',
  );
}